version: '4.31.0'

services:
  expo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19000:19000" # Expo server
      - "19001:19001" # Expo LAN
      - "19002:19002" # Expo Web
    volumes:
      - .:/app
    command: npm start
    environment:
      - EXPO_DEBUG=true
